AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics:
  Enabled: false

Layout/LineLength:
  Max: 120
